name: "CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  show-github-context:
    timeout-minutes: 1
    runs-on: ubuntu-22.04
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - run: echo $GITHUB_CONTEXT

  test-happy-path:
    runs-on: ubuntu-22.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_DEFAULT_REGION: us-east-1
      AWS_S3_KEY_PREFIX: test/happy-path/containers-${{ github.run_number }}
    steps:
      - name: Checkout
        timeout-minutes: 1
        uses: actions/checkout@v2
      - name: Install Docker Compose
        timeout-minutes: 1
        run: |
          sudo apt -qq install -y docker-compose
          docker-compose --version
      - name: Create Expected Backup
        timeout-minutes: 1
        run: |
          cd test/happy-path
          ./local.sh
      - name: Run Containers
        timeout-minutes: 1
        run: |
          cd test/happy-path
          docker-compose up -d --build
      - name: Run Backups
        env:
          COMPOSE_INTERACTIVE_NO_CLI: 1
        run: |
          cd test/happy-path
          docker-compose exec -T backup /bin/sh /backup.sh
          sleep 3
          docker-compose exec -T backup /bin/sh /backup.sh
      - name: Stop Containers
        if: ${{ always() }}
        run: |
          cd test/happy-path
          docker-compose logs
          docker-compose down
      - name: Install AWS CLI
        timeout-minutes: 1
        run: |
          sudo apt -qq install -y awscli
          aws --version
      - name: Check Backups
        run: |
          aws s3 cp s3://$AWS_S3_BUCKET . --recursive --exclude "*" --include "$AWS_S3_KEY_PREFIX-*"
          find . -name '*.tar.gz' | grep $AWS_S3_KEY_PREFIX | xargs md5sum
          find . -name '*.tar.gz' | grep $AWS_S3_KEY_PREFIX | xargs cmp --silent $1 backup.tar.gz
