name: "CI"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  show-github-context:
    timeout-minutes: 1
    runs-on: ubuntu-22.04
    env:
      GITHUB_CONTEXT: ${{ toJson(github) }}
    steps:
      - run: echo $GITHUB_CONTEXT

  test-happy-path:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Docker Compose
        run: |
          sudo apt install -y docker-compose
          docker-compose --version
      - name: Install AWS CLI
        run: |
          sudo apt install -y awscli
          aws --version
      - name: Create Expected Tarfile
        run: |
          ./test/happy-path/local.sh
      - name: Run Containers
        run: |
          echo "Hello world"
